### ISSUE TITLE
Design a Logo for PWC!

### ISSUE THREAD

**Issue by zziz** [zziz/pwc#10]
I'm looking for a designer who can volunteer a design a logo for PWC. Please post your design here.

**Comment by IronPark** [comment]
## "Paper" with "Code"
![pwc_](https://user-images.githubusercontent.com/4973597/45736139-0cd68f80-bc25-11e8-9f52-7712ba365432.png)

**Comment by zziz** [comment]
Dear @IronPark, thank you for your great work. Perhaps, I should have been more clear about "looking for designer" part. To be clear, I'm looking for a designer who can volunteer the designing. I will include the designers name and link to main page though.

**Comment by zziz** [comment]
Dear @IronPark, if you do volunteer it, i will go ahead and include it to pwc page :+1: :)

**Comment by IronPark** [comment]
@zziz What kind of design do you need? I am not a professional designer, but I am willing to help as long as I can.

**Comment by zziz** [comment]
Dear @IronPark, above design looks nice! Please make one modification - I want to include it to main README.md page, so its its size must be as height/width = 1/3 (ex. 900x300) and I it would be great if final image file had "Papers with Code" text in it (alongside with above logo).
To sum up, lets say LOGO means above your design of logo, then final image should look like [Papers with Code + LOGO]. If it is not clear, please let me know.

**Comment by IronPark** [comment]
![pwc-title-0](https://user-images.githubusercontent.com/4973597/45830799-d853f800-bd38-11e8-92bb-22af08d45166.jpg)
@zziz how about this?

**Comment by zziz** [comment]
Dear @IronPark , "Paper with Code" v1 looks great! One small change please - It must be "Papers with Code", i.e. paper is plural :) Thank you in advance :+1:

**Comment by IronPark** [comment]
@zziz 
![pwc-title-fix](https://user-images.githubusercontent.com/4973597/45854556-a36e9200-bd86-11e8-8836-2f9bf632a4dc.jpg)

**Comment by zziz** [comment]
Thank you very much @IronPark! I will include v1 to main page tonight :)
